/**
 * Constantes compartilhadas entre frontend e backend
 */

export const JOB_CATEGORIES = [
  "Acompanhante Terapêutico",
  "Administrativo",
  "Aplicador ABA",
  "Coordenador",
  "Estágio",
  "Fisioterapeuta",
  "Fonoaudióloga",
  "Limpeza",
  "Musicoterapeuta",
  "Nutricionista",
  "Psicólogo",
  "Psicomotricista",
  "Psicopedagogo",
  "Recepcionista",
  "RH",
  "Terapeuta Ocupacional",
] as const;

export type JobCategory = (typeof JOB_CATEGORIES)[number];

export const JOB_LOCATIONS = [
  "Araraquara",
  "Atibaia",
  "Barueri",
  "Belém",
  "Belo Horizonte",
  "Campinas",
  "Cotia",
  "Cubatão",
  "Curitiba",
  "Fazenda Rio Grande",
  "Fortaleza",
  "Goiânia",
  "Guarujá",
  "Guarulhos",
  "Indaiatuba",
  "Juiz de Fora",
  "Jundiaí",
  "Maceió",
  "Mauá",
  "Niterói",
  "Osasco",
  "Porto Alegre",
  "Praia Grande",
  "Ribeirão Preto",
  "Rio de Janeiro",
  "Rio Verde",
  "Santo André",
  "Santos",
  "São Caetano do Sul",
  "São José do Rio Preto",
  "São José dos Campos",
  "São Paulo",
  "São Vicente",
  "Saquarema",
  "Socorro",
  "Sorocaba",
  "Vitória",
] as const;

export type JobLocation = (typeof JOB_LOCATIONS)[number];

export const JOB_SOURCES = ["indeed", "linkedin", "glassdoor", "catho"] as const;
export type JobSource = (typeof JOB_SOURCES)[number];

export const JOB_STATUS = ["pending", "approved", "rejected", "published"] as const;
export type JobStatus = (typeof JOB_STATUS)[number];

export const STATE_MAP: Record<string, string> = {
  "Acre": "AC",
  "Alagoas": "AL",
  "Amapá": "AP",
  "Amazonas": "AM",
  "Bahia": "BA",
  "Ceará": "CE",
  "Distrito Federal": "DF",
  "Espírito Santo": "ES",
  "Goiás": "GO",
  "Maranhão": "MA",
  "Mato Grosso": "MT",
  "Mato Grosso do Sul": "MS",
  "Minas Gerais": "MG",
  "Pará": "PA",
  "Paraíba": "PB",
  "Paraná": "PR",
  "Pernambuco": "PE",
  "Piauí": "PI",
  "Rio de Janeiro": "RJ",
  "Rio Grande do Norte": "RN",
  "Rio Grande do Sul": "RS",
  "Rondônia": "RO",
  "Roraima": "RR",
  "Santa Catarina": "SC",
  "São Paulo": "SP",
  "Sergipe": "SE",
  "Tocantins": "TO",
};

// Mapa de cidades para estados
export const CITY_STATE_MAP: Record<string, string> = {
  "Araraquara": "SP",
  "Atibaia": "SP",
  "Barueri": "SP",
  "Belém": "PA",
  "Belo Horizonte": "MG",
  "Campinas": "SP",
  "Cotia": "SP",
  "Cubatão": "SP",
  "Curitiba": "PR",
  "Fazenda Rio Grande": "PR",
  "Fortaleza": "CE",
  "Goiânia": "GO",
  "Guarujá": "SP",
  "Guarulhos": "SP",
  "Indaiatuba": "SP",
  "Juiz de Fora": "MG",
  "Jundiaí": "SP",
  "Maceió": "AL",
  "Mauá": "SP",
  "Niterói": "RJ",
  "Osasco": "SP",
  "Porto Alegre": "RS",
  "Praia Grande": "SP",
  "Ribeirão Preto": "SP",
  "Rio de Janeiro": "RJ",
  "Rio Verde": "GO",
  "Santo André": "SP",
  "Santos": "SP",
  "São Caetano do Sul": "SP",
  "São José do Rio Preto": "SP",
  "São José dos Campos": "SP",
  "São Paulo": "SP",
  "São Vicente": "SP",
  "Saquarema": "RJ",
  "Socorro": "SP",
  "Sorocaba": "SP",
  "Vitória": "ES",
};
